# NumPy

NumPy, or Numpy, serves as a pivotal Linear Algebra Library within the Python programming realm. Its significance in the realm of Data Science using Python is underscored by the fact that virtually all the libraries within the PyData Ecosystem hinge on NumPy as a foundational cornerstone.



## Installing NumPy

**If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy

**If you want to install NumPy by going to your local environment instead of anaconda the do that by typing**

    !pip install numpy

## Importing NumPy

After successfully installing NumPy, you can bring it into your code by importing it as a library.

In [ ]:
import numpy as np

# About Numpy Arrays

Essentially, NumPy arrays can be categorized into two types: vectors, which are exclusively 1-dimensional arrays, and matrices, which are 2-dimensional (though it's worth noting that a matrix can still consist of only one row or one column). We can create an array by directly converting a list or list of lists in python:

In [ ]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [ ]:
np.array(my_list)

array([1, 2, 3, 4, 5])

In [ ]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## NumPy Built-in Methods



### arange Method

Provide values that are uniformly distributed within a specified range.

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones Method

Generate arrays of zeros or ones

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace Method
Provide numbers that are evenly distributed within a defined range.

In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye Method

Used to create an identity matrix

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random Number Creation

### rand Method
Generate an array with the specified shape and fill it with random samples from a uniform distribution ranging from 0 (inclusive) to 1 (exclusive).

In [ ]:
np.random.rand(2)

array([0.79398074, 0.073833  ])

In [ ]:
np.random.rand(5,5)

array([[8.08051072e-01, 7.48189857e-01, 4.76290982e-01, 9.38855849e-01,
        2.51045369e-01],
       [4.17358593e-01, 8.22344692e-01, 7.20145906e-01, 7.49573883e-01,
        4.24470088e-01],
       [9.54651041e-01, 7.15757450e-01, 2.19768238e-01, 9.78621825e-01,
        7.87755367e-01],
       [4.27087334e-01, 9.56596324e-01, 1.00249623e-04, 4.64708976e-01,
        3.98568116e-01],
       [4.01739355e-01, 4.41705886e-01, 8.76988931e-01, 1.87305707e-01,
        3.81617533e-01]])

### randn Method

Provide a sample (or samples) from the standard normal distribution. Unlike the uniform distribution of rand, this distribution is not uniform.

In [ ]:
np.random.randn(2)

array([-1.23238971,  0.28256853])

In [ ]:
np.random.randn(5,5)

array([[ 0.26742984, -0.79299952, -0.67711358,  0.7848118 ,  0.85685346],
       [-0.67279964, -1.25013645,  0.64654906,  0.20412121, -0.14172189],
       [ 0.73452854,  0.37722419,  0.06294724, -0.51998   ,  0.29993638],
       [-0.8201908 ,  0.64412727,  1.63340352,  0.33826118, -0.47752746],
       [ 0.54519508,  0.29464108,  1.30087617, -0.40969791, -0.78284198]])

### randint Method
Generate random integers within the inclusive range of 'low(0)' to the exclusive range of 'high(1)'.

In [ ]:
np.random.randint(1,100)

24

In [ ]:
np.random.randint(1,100,10)

array([46, 31, 81,  4, 67, 68, 47, 35, 28, 34])

## NumPy Array Attributes and Built-in Methods

In [ ]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:

ranarr

array([ 6,  9, 17, 16, 38, 48, 47, 28,  3, 37])

## Reshape Method
Provide an array with a modified shape while retaining the same data.

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### Numpy Aggregate Methods(max,min,argmax,argmin)

In [ ]:
ranarr

array([ 6,  9, 17, 16, 38, 48, 47, 28,  3, 37])

In [ ]:
ranarr.max()

48

In [ ]:
ranarr.argmax()

5

In [ ]:
ranarr.min()

3

In [ ]:
ranarr.argmin()

8

## Shape Attribute

The shape is a characteristic possessed by arrays, and it is not a method but an attribute in NumPy.

In [ ]:
arr.shape

(25,)

## Reshape Attribute

The reshape attribute allows arrays to be reconfigured into a new shape without altering the underlying data.

In [ ]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(1,25).shape

(1, 25)

In [ ]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
arr.reshape(25,1).shape

(25, 1)